### ISSUE TITLE
Jet cli hangs on Windows

### ISSUE THREAD

**Issue by rwfeather** [codeship/codeship-pro-tutorial#15]
Hi there, this is the best place I could find for this issue and I apologize if it's already been addressed/folded into upcoming changes.

I am attempting to do local jet runs on my Win7 dev machine with Docker Toolbox installed and confirmed to be working. But the command line utility will intermittently hang and be unresponsive to ctrl-c when I call it. Something as simple as `jet --version` will hang. I have successfully run `jet steps` a handful of times but now it immediately hangs virtually every time.

I understand docker and related tools aren't exactly first-class citizens in Windows < 10, but it frustrates me as I've had it work perfectly a few times. Are there any configuration steps that might fix this issue, or should I look into running a different environment?

Note: I've also tried the dynamically linked binary provided in the install instructions.

**Comment by mlocher** [comment]
@rwfeather thanks for getting in touch, we'll look into this and I get back to you as soon as I have some more information at hand. (Unfortunately I don't have access to a Windows VM at the moment, so I'll have to wait for somebody else to verify and look into this.)

**Comment by rheinwein** [comment]
Hey @rwfeather -- could you provide a bit more information that can help us get to the root of the problem?

* Jet version (I'd recommend downloading the newest version [here](https://documentation.codeship.com/docker/getting-started/installation/))
* Docker Version (`docker info` output would be great)
* Docker Machine provider (VirtualBox, AWS, etc)

Are you able to repro the problem using Docker for Windows?

**Comment by rwfeather** [comment]
I would be glad to.

- Using the 1.14.4 binary
- [Here is the output of `docker info`](https://github.com/codeship/jet-tutorial/files/619344/docker.txt)
- Virtualbox
- I haven't tried Docker for Windows to see if the problem exists there. I would, but I don't have a machine set up that supports it.

Thank you, and let me know if you need more.

**Comment by mauromorales** [comment]
I'm closing this issue since there has been no followup in a long time. We now have jet client version 2.11.0. If this is still a problem, feel free to re open with updated info. Thanks!

**Comment by LarsFronius** [comment]
Oooh, I remember fixing this sometime in 2017. Never knew about this GH issue though 😱

**Comment by mauromorales** [comment]
Thanks for fixing it @LarsFronius! No worries, just doing some cleanup here and there
